---
# add Puppetlabs repository in Amazonlinux

- set_fact:
    el_version: "{{ (ansible_service_mgr == 'systemd') | ternary('7', '6') }}"

- name: Amazonlinux | Add Puppetlabs rpm key
  rpm_key:
    state: present
    key: "{{ item }}"
  loop:
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet'
    - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet-20250406'

- name: Amazonlinux | Add Puppetlabs repository
  yum_repository:
    name: puppet{{ puppet_version }}
    description: "Puppet {{ puppet_version }} Repository el {{ ansible_distribution_major_version }} - $basearch"
    baseurl: http://yum.puppetlabs.com/puppet{{ puppet_version }}/el/{{ el_version }}/$basearch
    gpgcheck: true
    gpgkey:
      - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet'
      - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet-20250406'
    enabled: true
    state: present

- name: Amazonlinux | Add Puppetlabs source repository
  yum_repository:
    name: puppet{{ puppet_version }}-source
    description: "Puppet {{ puppet_version }} Repository el {{ ansible_distribution_major_version }} - Source"
    baseurl: http://yum.puppetlabs.com/puppet{{ puppet_version }}-nightly/el/{{ el_version }}/SRPMS
    gpgcheck: true
    gpgkey:
      - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet'
      - 'http://yum.puppetlabs.com/RPM-GPG-KEY-puppet-20250406'
    enabled: true
    state: "{{ puppetlabs_repo_source }}"
